### PR TITLE
Refactor Front End

### PR DESCRIPTION
**Pull request by kmcgurty**
This will be everything that should be refactored in the front end of Bolt. Some of these will definitely be subjective, but I'll try to keep it as objective as possible. As I go through the app, I'll continue to add more to this list. As they get fixed, I'll check them off.

**General Guidance:**
- [x] Svelte [Stores](https://svelte.dev/docs/svelte-store) shouldn't be overused. Svelte generally handles reactivity for you, but there are cases when stores are helpful. Svelte 5 helps make this more clear, but we can work on upgrading everything after this PR.
- [x] Window events (onload, onunload) should be avoided. Svelte has its own [lifecycle functions](https://svelte.dev/docs/svelte) hooks
- [x] Duplicate Svelte code can be wrapped into components
- [x] State variables should be scoped to a component. For eg, keeping track if a modal is open can be handled by a Modal component, not globally across the app
- [x] [Returning early](https://gomakethings.com/the-early-return-pattern-in-javascript/) can help readability and prevents unnecessary indentation
- [x] Type casting creates unsafe code in TS. Usually you want to avoid manually casting things, or use generics
- [x] It's very rare to use classic `.querySelector` or `.getElementById` code in Svelte. You can usually can bind the element to a variable and access it that way

**Specific Changes**
- [x] Replace msg/err with a Logger utility class
- [x] Replace Backdrop.svelte with a generic Modal.svelte that can handle its own open/close state
  - [x] Todo: PluginMenu is broken? I couldn't figure out how to get it loaded, anyway
  - [x] Todo:  In app.svelte, the {#if} branches for the modals should go away. I started doing this, but other code needs to be refectored first
- [x] I think most of the stores in `main.ts` can be put somewhere else, and likely not be a store. Not sure on the details yet.
- [x] The majority of main.ts can be cleaned up and reorganized elsewhere. At first glance, we can probably create a BoltService.ts, and maybe an AuthService.ts
- [x] Create a Dropdown.svelte, replace the dropdown code in Account.svelte with this new component
- [x] When using the select element, you can bind the value of an option to any type of variable. The on:change will then have that value in the event. Namely in Launch.svelte, this will remove the extra `data-id` code.

This is quite a bit, so it'll take me some time since I have a full time job - probably a week or two. Let me know if anyone has any problems with the proposed changes. @smithcol11 I'm not sure if you have any pending changes on your end, but this will likely break whatever you have going on. Let me know if we need to chat outside of github and we can.

### CODE REVIEW

**Comment by kmcgurty** [comment]
@Adamcake @smithcol11 I believe this is ready to merge assuming there's no issues with Windows or MacOS. It'd be helpful if both of you could poke around with all the changes and see if anything's broken. There's still some outstanding changes related to `PluginModal.svelte` and `functions.ts`, but I left most of that code untouched. Essentially, the majority of the front end still works (and looks) the same, except for authentication. Instead of the code flow going back and forth with the popup that's opened, the popup does everything related to auth. Otherwise, a lot of the changes were removing the unnecessary writable variables, organizing functions into different services, and making those functions either return a result, or a "promisfied" result.

An important note: since I changed the config and auth code so much, once this goes live, everyone's settings will be erased and they will have to sign in again. If this is a problem, I can see about writing a compatibility layer between the new and old config/creds.

I've added a `todo:` for everything that's left. Namely:
* I think it'd be less obscure if we had basically 2 routes: `index.html` and  `authenticate.html`. Right now, `main.ts` will essentially render a different app if it detects the current window as a popup or if certain params are present. If we instead had `authenticate.html`, we could make the `launcher-redirect` path move to `/authenticate.html` instead of `index.html`.
* `store.ts` has one remaining Writable that I wasn't sure what to do with. The plugin stuff is complex, so I left it alone since this PR has already taken long enough. Once that variable is gone, `store.ts` can go away.
* All of the launch* functions have quite a bit of code going on inside of them. It didn't make too much sense to refactor all those, but potentially a goal in the future is to break up those functions and reduce duplicate code.

Overall, the front end is in a pretty good state, but there is a change or two I'd potentially need to think about some more or consult with you guys about. For example: I'm not a huge fan of `BoltService.findSession` and `BoltService.findAccount`. It leads to instances where you always have to check if the result is undefined. Something we could do instead is only show a login button if no user is signed in - this way we could potentially just assume those aren't undefined? There's some other TypeScript stuff related to that in order to get that working, but just a thought.

Very curious to hear both of your thoughts about these changes.

**Comment by Adamcake** [comment]
Thanks for doing this. The code looks good, I can see a couple of problems with functionality so far though:
- when I first launch Bolt with no config files saved at all, if I select a different character and then launch a game, then close and re-open Bolt, the character drop-down will revert to the default instead of the one I selected. It does work correctly on all subsequent launches, though.
- in OSRS, the game client drop-down always shows HDOS, but in fact it only ever launches RuneLite. (also can we make RuneLite the default? It seems to be what a vast majority of users are here for.)
- when I add or remove an RS3 plugin and then close the window, that doesn't get saved. It does get saved if I launch the game, or do something else that would change the config before closing the window.

**Comment by Adamcake** [comment]
> Something we could do instead is only show a login button if no user is signed in - this way we could potentially just assume those aren't undefined?

You could make the "play" button greyed out with a tooltip if the result would be undefined. Would that work?

**Comment by kmcgurty** [comment]
> when I first launch Bolt with no config files saved at all, if I select a different character and then launch a game, then close and re-open Bolt, the character drop-down will revert to the default instead of the one I selected. It does work correctly on all subsequent launches, though.

Fixed in [aca9653](https://github.com/Adamcake/Bolt/pull/50/commits/aca9653c6a8327e717110b542064e3a8c9bcfdfc)

> in OSRS, the game client drop-down always shows HDOS (i.e. I can't change it), but in fact it only ever launches RuneLite. (also can we make RuneLite the one that's selected by default? It seems to be what a vast majority of users are here for.)

I wasn't able to reproduce this? I made RuneLite default (good call), but for me I can pick RuneLite or HDOS and both run fine. If I close Bolt and re-open it, the last option I picked is selected. I realized Official was able to be selected even though it's  not supported on Linux so I fixed that. Maybe that's related somehow?

> when I add or remove an RS3 plugin and then close the window, that doesn't get saved. It does get saved if I launch the game, or do something else that would change the config before closing the window.

Fixed in [5d4ccad](https://github.com/Adamcake/Bolt/pull/50/commits/5d4ccad9b95866a9d66d1cbf3d49417dc30c52f7)

> You could make the "play" button greyed out with a tooltip if the result would be undefined. Would that work?

Yes I agree with this, but it's a bit unrelated to this PR

**Comment by Adamcake** [comment]
> I wasn't able to reproduce this?

Looks like I built the master branch instead of the `refactor/front-end` branch, sorry about that. I'll review the rest tomorrow.

**Comment by Adamcake** [comment]
These drop-downs are off-center, and the modals for settings and plugins are all left-justified when they were previously centered.
image

**Comment by Adamcake** [comment]
Also the modals close by clicking on their edges. (outer 8px or so, by eye)

**Comment by Adamcake** [comment]
```17:18:58 - Game launch status: 'OK'
17:18:58 - Downloading HDOS... 100.0%
17:18:58 - Downloading HDOS... 15.0%
17:18:58 - Downloading HDOS...
17:18:57 - Save config status: 'OK'
17:18:31 - Game launch status: 'OK'
17:18:31 - Downloading RuneLite... 100.0
17:18:31 - Downloading RuneLite... 0.0
17:18:30 - Downloading RuneLite...
17:18:30 - Save config status: 'OK'
17:17:15 - Game launch status: 'OK'
17:17:14 - Downloading RS3 client... 100.0%
17:17:14 - Downloading RS3 client... 0.0%
17:17:13 - Downloading RS3 client...
17:17:13 - Save config status: 'OK'
```

For these messages, the percentage is meant to change in-place rather than posting a new message. RuneLite is also missing a `%` symbol.

**Comment by kmcgurty** [comment]
Not sure how I missed those styling issues, but they should be resolved. I noticed the plugin menu also wasn't center aligned, so that's fixed as well. `Modal.svelte` had some padding on it for some reason, that's gone now. Finally, I added an `updateLogAtIndex` function and changed the download messages to use it instead of adding a new message every time.

This is very small, but I noticed with one of my previous commits, if there's no config, it saves one to disk (to fix the problem where it wasn't saving the first time). The saveConfig function logs out whenever it saves, but to a new user that's opened the app for the first time, it looks like this:

image

Should I make it not log out the config was saved and instead make it say something else? Or nothing at all?

**Comment by Adamcake** [comment]
Hmm, I think if it's overwriting a file then it's right that it should inform the user of that. Maybe in future we can make those messages less clinical, like just "config saved" if the status is 200 and print the response body for anything else.

**Comment by kmcgurty** [comment]
I agree with that. At some point I can make another PR that adds any features you want. My thought is I can add tooltips and make a Button component separately. I already added a Dropdown and Modal. We could also re-imagine the log view and instead have toast notifications if you'd like. Totally up to you though.

**Comment by Adamcake** [comment]
Okay, last thing (probably) for this PR: if you're logged into multiple Jagex accounts, when you switch between them, the character select will always be blank. This removes a feature: the current release of Bolt remembers which character is selected for each Jagex account and stores that in the config file, but it looks like you've changed the config file to just keep one character overall. Is there a reason you changed that?

**Comment by kmcgurty** [comment]
> Okay, last thing (probably) for this PR: if you're logged into multiple Jagex accounts, after you switch between them, the character select will always be blank. The current release of Bolt remembers which character is selected for each Jagex account and stores that in the config file, but it looks like you've changed the config file to just keep one character overall. Is there a reason you changed that?

Sorry for the delay - breaking it wasn't intentional, just an oversight when I was trying to simplify things. This should be fixed now, could you try to find bugs with it? I tried logging in/out, selecting/unselecting - it feels robust to me. 

---

Unrelated but probably helpful to explain: one of the things I did when I refactored all this stuff is I changed the terminology around. We might want to put this in the readme? Essentially:
* user: details about a single jx user
* account (character): each user can contain multiple accounts
* session: combines a user and its accounts. there's a global array that has all of the sessions and these are what's saved to disk

As I was making this most recent change, I had a thought. For some background, when I play my main, I sometimes play RS3, but usually play OSRS/Runelite. On my ironman, I only ever play OSRS/Runelite. It'd probably require a UI change to make it flow better, but my thought is we could save the game and client per user? For eg. if I select my ironman, it'd auto select OSRS/Runelite for me if the last game I played was my main/RS3.

Because of how things are laid out now, it'd be pretty bad UX. Changing a select in the middle of the page would basically change whole content (changing RS3 > OSRS). As for changing the UI, my thought is something like this (this is a very rough idea):

image

Move the user/account select to the top, and the game/client can be in the middle of the page. This could also play into what I was suggesting before where if no user is signed in we can show different buttons or a different page all together.

Anyway, this PR should be 1:1 with the production app. Let me know if there's any other issues.

**Comment by Adamcake** [comment]
Yup, good to go, thanks.

One final odd detail I've noticed, which I'm not sure if it was introduced by your PRs or not, is that if you make the window horizontally small, all the fonts get smaller. That can end up looking strange on tiling WMs but it's not really a concern.

**Comment by kmcgurty** [comment]
Oh, yeah that would be this line [here](https://github.com/Adamcake/Bolt/blob/8b8be172d6bc6771db6a2268aeae5e1727c4311c/app/src/lib/Components/MainLayout.svelte#L10) in MainLayout.svelte. Specifically `text-xs sm:text-sm md:text-base`, it should probably just be `text-base`. You can read more about the screen size prefixes [here](https://tailwindcss.com/docs/responsive-design#working-mobile-first) and how they work.

**Pull request merged**
